# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b031558c6024cec0435c8603ad9c3d3087a21d81d222dd019d15c80f35802ec72dbcd40a9b2f67bbb0f2c30c9ecad5cc9e2df3185f383e881d71c3b7deff3f

test:
  secret_key_base: 344be973453c15d9630d8370232261d75687844f291d079d23c31843b7e97cbe4f115381ea7fdf76b6ffb1c862ad82aa4ed71f1618c2a3ecb87e12aac1c8e907

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
